# Generated by Django 5.2.5 on 2025-09-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_alter_image_description_alter_image_image_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
